### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ocramz** [ocramz/depq#1]

**Comment by HirotoShioi** [comment]
Is it okay if I work on this issue? If yes, I have some questions

1. Do you have any libraries you have in mind that you want to use for testing? If not, I'll use [QuickCheck](https://hackage.haskell.org/package/QuickCheck-2.14) with [hspec](https://hackage.haskell.org/package/hspec)

2. Is there any formatting tool or set of rules that you're using for this project? (This is just for me to facilitate the formatting process).

If you're interested in what kind of tests that I'll be implementing, have a look at [this module](https://github.com/HirotoShioi/functional-correctness-with-quickcheck/blob/master/src/Examples/BSTSpec.hs)

**Comment by ocramz** [comment]
Hi! Sure, I'd really appreciate if you contributed here! 

* hspec + QuickCheck are perfectly fine
* No hard formatting rules, the style you used in that module is perfectly readable.

Thank you!

**Comment by ocramz** [comment]
Closed by #2
